version: '3.8'

services:
  backend:
    build: ./backEnd
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=your_database_url
    networks:
      - app-network

  frontend:
    build: ./frontEnd
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge