version: '3.8'

volumes:
  data:



  backend:
    build: 
      context: .
      dockerfile: Dockerfile.app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`fastapi.localhost`)"
      - "traefik.http.services.fastapi.loadbalancer.server.port=8000"
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:@host.docker.internal:3306/product
    networks:
      - backend-network
    volumes:
      - data:/app/data