version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=your_database_url
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge